[package]
name = "tryte-compress"
version = "0.1.0"
authors = ["Martyn Janes <martyn@obany.com>"]
edition = "2018"

[dependencies]
lazy_static = "*"

[dev-dependencies]
criterion = "0.2"
rand = "0.6.5"

[[bench]]
name = "benchmark"
harness = false
